------------------------------------------------------------------------------------------------------
---Copilot Bindings:
--- Panel:
--- - :Copilot panel - open panel
--- - Jump to previous suggestion - [[
--- - Jump to next suggestion - ]]
--- - Accept suggestion - <CR>
--- - Refresh - gr
--- Inline:
--- - Accept - <M-a>
--- - Dismiss - <C-]>
------------------------------------------------------------------------------------------------------
-- return {
--   'zbirenbaum/copilot.lua',
--   cmd = 'Copilot',
--   event = 'InsertEnter',
--   build = ':Copilot auth',
--   opts = {
--     suggestion = {
--       enabled = true,
--       auto_trigger = true,
--       keymap = {
--         accept = '<M-a>',
--       },
--     },
--     panel = {
--       enabled = true,
--       auto_refresh = true,
--       layout = {
--         position = 'right',
--         ratio = 0.3,
--       },
--     },
--     filetypes = {
--       ['.'] = true, -- enable all filetypes
--     }
--   }
-- }
return {}
